#17 - Action migration to composite
AbsaOSS/living-doc-generator pull request #18
Opened 2024-07-03 07:01 UTC by miroslavpojer

- Updated action.yml file.
- Renamed and updated main python file.

Closes #17

2024-07-03 07:03 UTC, miroslavpojer commented
Release notes:
- Action migrated to composite type.
- Renamed main control script.
- Prepared TODO with several proposals to follow.

2024-07-17 17:10 UTC, MobiTikula requested changes
Besides the comments I suggest to update .gitignore file.

2024-07-18 05:31 UTC, miroslavpojer commented on README.md
> +For running just one script at the time, add the following commands to the shell script:
Removed. Maybe it is a result of the merge.

2024-07-18 05:32 UTC, miroslavpojer commented on src/living_documentation_generator.py
> +        result = subprocess.run(['python3', script_name], env=env, text=True, capture_output=True, check=True)
The usage of Python 3 should be more generic here. In the next PRs, this approach will be removed.

2024-07-18 05:35 UTC, miroslavpojer commented on src/living_documentation_generator.py
> +def extend_args():
In the current solution, we have multiple scripts that share config across system env variables. Here, we define paths in one place in the controller.

2024-07-18 05:36 UTC, miroslavpojer commented
> Besides the comments I suggest to update .gitignore file.

What do you suppose? I do not see any change request.

2024-07-18 06:50 UTC, MobiTikula commented
I suggest to remove `node_modules` and  `/package-lock.json`, because they keep ignored files in old versions of project, despite we have a composite action now.

2024-07-18 07:14 UTC, MobiTikula commented
I suggest to remove `node_modules` and  `/package-lock.json`, because they keep ignored files in old versions of project, despite we have a composite action now.

Also I still see [index.js](https://github.com/AbsaOSS/living-doc-generator/blob/feature/17-action-migration-to-composite/src/index.js) in the project, is it intentionally? Composite actions should not use javascript at all via: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action and also example Composite actions.

2024-07-18 08:12 UTC, miroslavpojer commented
> I suggest to remove `node_modules` and `/package-lock.json`, because they keep ignored files in old versions of project, despite we have a composite action now.
> 
> Also I still see [index.js](https://github.com/AbsaOSS/living-doc-generator/blob/feature/17-action-migration-to-composite/src/index.js) in the project, is it intentionally? Composite actions should not use javascript at all via: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action and also example Composite actions.

Great findings. All of them should be fixed.

2024-07-18 08:14 UTC, MobiTikula approved these changes

2024-07-18 08:21 UTC, merged